// ConceptStore: the deep module that owns concept identity, metadata, and
// body for one workspace's wiki. Its interface is the test surface for
// everything concept-shaped — wiki-scan (hash + diff), wiki-graph (nodes +
// edges), and files.ts (preview) all project onto it instead of re-walking
// and re-deriving concept identity.
//
// What lives here (the deep implementation):
//   - recursive walk of wiki/
//   - conceptId derivation (strip an optional `wiki/` prefix + `.md`)
//   - reserved/kind knowledge (index.md, log.md are NOT concepts)
//   - frontmatter parsing + metadata extraction
//
// What callers keep (their own policies):
//   - wiki-scan: hashing body + diffing snapshots
//   - wiki-graph: extracting links (graph policy) + localizing index/log
//     labels (graph vocabulary stays out of the store)
//   - files.ts: single-file preview + text/binary fallback for non-wiki files
//
// See CONTEXT.md for the domain terms (Concept, conceptId, kind, reserved).
import { readFile, readdir } from "node:fs/promises";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import { parseDocument } from "./frontmatter.ts";
import { mainT } from "./i18n.ts";

/** Reserved wiki filenames — generated by the extension, not agent-authored
 *  concepts. Knowledge of WHICH files are reserved lives here; the policy of
 *  whether to include them lives in each caller (via `kind`). */
const RESERVED = new Set(["index.md", "log.md"]);

export type ConceptKind = "concept" | "index" | "log";

/** One wiki markdown file, fully read + parsed. Each caller reads the slice
 *  it needs: wiki-scan hashes `body`, wiki-graph reads `body`/`title`/`type`/
 *  `tags`, files.ts displays `body` + `title`/`description`/`type`. */
export interface Concept {
  /** Stable id: POSIX path relative to wiki/, without `.md`. */
  readonly conceptId: string;
  /** `concept` for ordinary files; `index`/`log` for the reserved filenames
   *  (matched by basename, anywhere in the tree). */
  readonly kind: ConceptKind;
  /** `frontmatter.title ?? frontmatter.type ?? conceptId`. */
  readonly title: string;
  /** `frontmatter.type ?? mainT("concept.untyped")`. */
  readonly type: string;
  readonly description: string;
  readonly tags: readonly string[];
  /** Frontmatter-stripped body. */
  readonly body: string;
  /** Raw `frontmatter.type` before the untyped fallback. Lets a caller tell
   *  "no type declared" apart from "type literally equals the untyped label". */
  readonly frontmatterType: string | undefined;
}

/** Recursive directory walk: skip dotfiles, yield POSIX relativePath + abs. */
async function walk(
  dir: string,
  root: string,
): Promise<readonly { relativePath: string; absolutePath: string }[]> {
  const out: { relativePath: string; absolutePath: string }[] = [];
  let entries: import("node:fs").Dirent[];
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    if (entry.name.startsWith(".")) continue;
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await walk(abs, root)));
    } else if (entry.isFile()) {
      const rel = relative(root, abs).split(sep).join("/");
      out.push({ relativePath: rel, absolutePath: abs });
    }
  }
  return out;
}

/** kind from the basename (matches wiki-scan/files reserved semantics:
 *  `sub/index.md` is reserved too, not just top-level). */
function kindOf(relativePath: string): ConceptKind {
  const name = relativePath.split("/").pop() ?? relativePath;
  if (!RESERVED.has(name)) return "concept";
  return name === "index.md" ? "index" : "log";
}

/** conceptId from a wiki-relative path: strip `.md`. */
function conceptIdOf(relativePath: string): string {
  return relativePath.endsWith(".md") ? relativePath.slice(0, -3) : relativePath;
}

/** Parse already-read content into a Concept. Shared by list + read-one. */
function buildConcept(relativePath: string, content: string): Concept {
  const parsed = parseDocument(content);
  const fm = parsed.frontmatter;
  return {
    conceptId: conceptIdOf(relativePath),
    kind: kindOf(relativePath),
    title: fm?.title ?? fm?.type ?? conceptIdOf(relativePath),
    type: fm?.type ?? mainT("concept.untyped"),
    description: fm?.description ?? "",
    tags: fm?.tags ?? [],
    body: parsed.body,
    frontmatterType: fm?.type,
  };
}

/** Read + parse one wiki markdown file. Returns null on read failure (the
 *  caller decides how to surface that). */
async function loadConcept(
  absolutePath: string,
  wikiRoot: string,
): Promise<Concept | null> {
  try {
    const content = await readFile(absolutePath, "utf8");
    const rel = relative(wikiRoot, absolutePath).split(sep).join("/");
    return buildConcept(rel, content);
  } catch {
    return null;
  }
}

export class ConceptStore {
  constructor(private readonly workspace: string) {}

  private wikiDir(): string {
    return join(this.workspace, "wiki");
  }

  /** Every concept in the wiki, excluding reserved files (`kind === "concept"`).
   *  Used by wiki-scan to build the hash snapshot for diffing. */
  async listConcepts(): Promise<readonly Concept[]> {
    const all = await this.listAll();
    return all.filter((c) => c.kind === "concept");
  }

  /** Every wiki markdown file, including `index.md`/`log.md` tagged with their
   *  `kind`. Used by wiki-graph to build nodes (it localizes index/log labels
   *  itself — graph vocabulary stays out of the store). */
  async listAll(): Promise<readonly Concept[]> {
    const wikiDir = this.wikiDir();
    const files = await walk(wikiDir, wikiDir);
    const concepts: Concept[] = [];
    for (const file of files) {
      if (!file.relativePath.endsWith(".md")) continue;
      const concept = await loadConcept(file.absolutePath, wikiDir);
      if (concept) concepts.push(concept);
    }
    return concepts;
  }

  /** Read one concept by workspace-relative path (e.g. `wiki/foo/bar.md` or
   *  `foo/bar.md`). Resolves under `wiki/`, so only wiki markdown files are
   *  returned; non-wiki or non-markdown paths yield null. Used by files.ts
   *  preview for wiki concepts. */
  async readConcept(relativePath: string): Promise<Concept | null> {
    const wikiRelative = stripWikiPrefix(relativePath);
    if (wikiRelative === null || !wikiRelative.endsWith(".md")) return null;
    const absolute = safeResolve(this.wikiDir(), wikiRelative);
    if (absolute === null) return null;
    return loadConcept(absolute, this.wikiDir());
  }

  /** Normalize a markdown link/path reference to a conceptId, or null for
   *  external / non-concept refs. Shared with wiki-graph's link extraction so
   *  the `wiki/` prefix + `.md` stripping rule is not duplicated. */
  normalizeRef(ref: string): string | null {
    let p = ref.trim().split("#")[0]!.split("?")[0]!;
    if (/^(https?:|mailto:)/.test(p)) return null;
    // strip leading slash (root-relative concept refs)
    p = p.replace(/^\//, "");
    // strip optional wiki/ prefix
    if (p.startsWith("wiki/")) p = p.slice("wiki/".length);
    if (!p.endsWith(".md")) return null;
    return p.slice(0, -3);
  }
}

/** Strip an optional `wiki/` prefix from a workspace-relative path. Returns
 *  null if the path is absolute or does not name a wiki file (so callers can
 *  short-circuit non-wiki paths). */
function stripWikiPrefix(relativePath: string): string | null {
  if (relativePath === "" || isAbsolute(relativePath)) return null;
  let p = relativePath;
  if (p.startsWith("wiki/")) p = p.slice("wiki/".length);
  else if (p === "wiki") return null;
  return p;
}

/** Resolve `relativePath` under `baseDir` and guard against traversal. Returns
 *  null when the resolved path escapes `baseDir` or `relativePath` is
 *  absolute. Mirrors the guard in files.ts (IPC-reachable, validate
 *  defensively). */
function safeResolve(baseDir: string, relativePath: string): string | null {
  if (relativePath === "" || isAbsolute(relativePath)) return null;
  const resolved = resolve(baseDir, relativePath);
  const rel = relative(baseDir, resolved);
  if (rel.startsWith(`..${sep}`) || rel === `..`) return null;
  return resolved;
}