import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useAtom, useAtomValue, useSetAtom } from "jotai";
import { ExternalLink, FileText, Folder as FolderIcon, Plus, Share2, Trash2 } from "lucide-react";
import { api } from "../ipc.ts";
import { useT } from "../i18n.ts";
import { reportAddFilesResult } from "../add-files.ts";
import { addFilesSummaryAtom, browserFolderAtom, browserModeAtom, folderVersionAtom, platformAtom, selectedFileAtom, toastAtom } from "../store.ts";
import { MarkdownView } from "../components/MarkdownView.tsx";
import { FileTree } from "../components/FileTree.tsx";
import { ContextMenu, type ContextMenuItem, type ContextMenuPosition } from "../components/ContextMenu.tsx";
import { RemoveConceptModal } from "../components/RemoveConceptModal.tsx";
import { GraphView } from "./GraphView.tsx";
import { ancestorDirs, buildFileTree, type TreeNode } from "../fileTree.ts";
import type { FileNode, FilePreview, Folder, RemovalPlan } from "../../shared/ipc-types.ts";

const FOLDERS: ReadonlyArray<{ id: Folder; labelKey: string }> = [
  { id: "input", labelKey: "folder.input.name" },
  { id: "wiki", labelKey: "folder.wiki.name" },
];

/** OS-adaptive i18n key for the "reveal in file manager" action. */
function revealLabelKey(platform: string): string {
  if (platform === "darwin") return "browser.reveal.finder";
  if (platform === "win32") return "browser.reveal.explorer";
  return "browser.reveal.fileManager";
}

interface CtxState {
  readonly node: TreeNode;
  readonly position: ContextMenuPosition;
}

/** Pending removal: the plan to confirm plus the target it was built for. */
interface RemovalState {
  readonly relativePath: string;
  readonly plan: RemovalPlan;
}

/** Generated by the wiki, so they cannot be removed on their own. */
const GENERATED_FILES = new Set(["index.md", "log.md"]);

/** Bundle subtrees that hold raw files rather than concepts. */
const NON_CONCEPT_DIRS = new Set(["archive", "trash"]);

/** Can this tree node be removed from the wiki? Only concepts qualify: the
 *  input folder holds un-ingested material, and the archive/trash subtrees
 *  hold originals and already-removed knowledge. */
function isRemovable(node: TreeNode, folder: Folder): boolean {
  if (folder !== "wiki") return false;
  if (NON_CONCEPT_DIRS.has(node.relativePath.split("/")[0]!)) return false;
  if (node.isDirectory) return true;
  return node.relativePath.endsWith(".md") && !GENERATED_FILES.has(node.name);
}

export function Browser(): JSX.Element {
  const t = useT();
  const setToast = useSetAtom(toastAtom);
  const setAddFilesSummary = useSetAtom(addFilesSummaryAtom);
  const platform = useAtomValue(platformAtom);
  const [folder, setFolder] = useAtom(browserFolderAtom);
  const [mode, setMode] = useAtom(browserModeAtom);
  const [selected, setSelected] = useAtom(selectedFileAtom);
  const folderVersion = useAtomValue(folderVersionAtom);
  // Derived once so the refresh effect can list it as an honest dependency.
  // Other folders' bumps are ignored to avoid needless re-lists.
  const activeFolderVersion = folderVersion[folder];
  const [nodes, setNodes] = useState<readonly FileNode[]>([]);
  const [preview, setPreview] = useState<FilePreview | null>(null);
  const [expanded, setExpanded] = useState<ReadonlySet<string>>(new Set());
  const [ctx, setCtx] = useState<CtxState | null>(null);
  const [removal, setRemoval] = useState<RemovalState | null>(null);
  const [removing, setRemoving] = useState(false);
  // Token guarding against stale overwrites: each refreshList call increments
  // it; the response is applied only if the token still matches. Without this,
  // rapid bursts could let a slow, older listFolder response clobber a fresher
  // one.
  const refreshToken = useRef(0);
  /** Same stale-response guard as `refreshToken`, for the preview read. */
  const previewToken = useRef(0);

  // Memoized on `folder` so the effect below can depend on it honestly
  // (no eslint-disable) without re-running on every render.
  const refreshList = useCallback(async (): Promise<void> => {
    const token = ++refreshToken.current;
    const list = await api.listFolder(folder);
    if (refreshToken.current !== token) return; // a newer refresh superseded us
    setNodes(list.success ? list.data : []);
  }, [folder]);

  async function addFiles(): Promise<void> {
    const result = await api.addInputFilesDialog();
    reportAddFilesResult(result, { setToast, setSummary: setAddFilesSummary, t });
    // No manual `refreshList()` here: the dialog writes to `input/`, the
    // FolderWatcher fires, `folderVersion.input` bumps, and the effect below
    // re-lists. Folder refresh stays in one place.
  }

  // Single refresh entry point for BOTH triggers: a folder switch (refreshList
  // identity changes) and a FolderWatcher version bump for the active folder
  // (activeFolderVersion changes). Honest deps, no eslint-disable; the
  // refreshToken guard inside refreshList discards stale responses during
  // rapid bursts.
  useEffect(() => {
    void refreshList();
  }, [refreshList, activeFolderVersion]);

  // Auto-expand all ancestor folders of the selected file so it stays
  // visible after a refresh or folder switch.
  useEffect(() => {
    if (!selected) return;
    // selected is `${folder}/${relativePath}`; strip the folder prefix.
    const prefix = `${folder}/`;
    if (!selected.startsWith(prefix)) return;
    const relativePath = selected.slice(prefix.length);
    const ancestors = ancestorDirs(relativePath);
    if (ancestors.length === 0) return;
    setExpanded((prev) => {
      const next = new Set(prev);
      let changed = false;
      for (const dir of ancestors) {
        if (!next.has(dir)) {
          next.add(dir);
          changed = true;
        }
      }
      return changed ? next : prev;
    });
  }, [selected, folder]);

  // Re-read the open file whenever its folder changes on disk, not just when
  // the selection changes: a removal rewrites index.md and the citing
  // concepts, and an ingest or an external edit changes files under the user's
  // cursor too. Keyed on the folder the SELECTION lives in (not the folder the
  // tree is showing), because a citation chip can open a wiki file while the
  // tree sits on input/.
  const selectedFolder = selected?.split("/")[0];
  const selectedFolderVersion =
    selectedFolder === "input" || selectedFolder === "wiki" ? folderVersion[selectedFolder] : 0;

  useEffect(() => {
    if (!selected) {
      setPreview(null);
      return;
    }
    const token = ++previewToken.current;
    void (async () => {
      const result = await api.getPreview(selected);
      // A newer read superseded us — dropping the stale response keeps a slow
      // response from clobbering a fresher one during a burst of changes.
      if (previewToken.current !== token) return;
      setPreview(result.success ? result.data : null);
    })();
  }, [selected, selectedFolderVersion]);

  const tree = useMemo(() => buildFileTree(nodes), [nodes]);

  function toggleDir(relativePath: string): void {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(relativePath)) next.delete(relativePath);
      else next.add(relativePath);
      return next;
    });
  }

  function handleContextMenu(node: TreeNode, position: ContextMenuPosition): void {
    setCtx({ node, position });
  }

  async function revealInFileManager(node: TreeNode): Promise<void> {
    await api.revealInFileManager(folder, node.relativePath, node.isDirectory);
  }

  /** Reveal the previewed file. `selected` is the selection key
   *  (`${folder}/${rel}`); the IPC call takes the folder-relative path. */
  async function revealSelectedFile(): Promise<void> {
    const prefix = `${folder}/`;
    if (!selected || !selected.startsWith(prefix)) return;
    await api.revealInFileManager(folder, selected.slice(prefix.length), false);
  }

  /** Ask what a removal would affect and open the confirmation. Nothing moves
   *  until the user confirms. */
  async function startRemoval(node: TreeNode): Promise<void> {
    const result = await api.planRemoval(node.relativePath);
    if (!result.success) {
      setToast({ message: t("remove.planFailed", { detail: result.error.message }), kind: "warning" });
      return;
    }
    setRemoval({ relativePath: node.relativePath, plan: result.data });
  }

  async function confirmRemoval(): Promise<void> {
    if (!removal) return;
    setRemoving(true);
    const result = await api.removeFromWiki(removal.relativePath);
    setRemoving(false);
    if (!result.success) {
      setToast({ message: t("remove.failed", { detail: result.error.message }), kind: "warning" });
      return;
    }
    // The preview would otherwise keep showing a file that is no longer there.
    // The tree itself re-lists via the FolderWatcher, like every other write.
    const removedKey = `wiki/${removal.relativePath}`;
    if (selected === removedKey || selected?.startsWith(`${removedKey}/`)) setSelected(null);
    setRemoval(null);
    setToast({ message: t("remove.done", { n: result.data.removed.length }), kind: "info" });
  }

  /** Handle a folder link click from a rendered `index.md` (or any markdown
   *  preview). `wikiDir` is a wiki-relative directory with no trailing slash
   *  (e.g. "wiki/species"). If the folder has an `index.md`, open it as the
   *  preview (the OKF convention — every indexed folder has one); otherwise
   *  navigate the Browser into the folder by expanding it in the tree and
   *  closing any open preview, so no stale preview state lingers.
   *
   *  `nodes` already lists every file under the wiki folder recursively (see
   *  `listFolder`'s walk), so the `index.md` existence check is a local set
   *  lookup — no extra IPC round-trip. */
  function openFolderLink(wikiDir: string): void {
    // wikiDir is wiki-relative, no trailing slash (e.g. "wiki/species"). For
    // the nodes lookup we need the folder-relative path (no "wiki/" prefix),
    // since listFolder lists files relative to the wiki folder.
    const dirRel = wikiDir.startsWith("wiki/") ? wikiDir.slice("wiki/".length) : wikiDir;
    const indexPath = dirRel ? `${dirRel}/index.md` : "index.md";
    // `nodes` reflects the CURRENTLY listed folder, so the index.md
    // existence check is only valid while the Browser is already on the wiki
    // folder. A folder link rendered from a non-wiki preview (rare) would
    // otherwise match against the wrong listing; in that case we skip the
    // index check and just navigate into the folder.
    const hasIndex =
      folder === "wiki" &&
      nodes.some((n) => n.relativePath === indexPath && !n.isDirectory);
    if (hasIndex) {
      setSelected(`${wikiDir}/index.md`);
      setFolder("wiki");
      return;
    }
    // No index.md (or not on the wiki folder): expand the folder in the tree
    // and drop any open preview to avoid a stale preview state. dirRel is
    // empty only for a link to the wiki root itself, which has no tree node
    // to expand — skip the setExpanded in that case to avoid a dead entry.
    setSelected(null);
    setFolder("wiki");
    if (dirRel) {
      setExpanded((prev) => {
        if (prev.has(dirRel)) return prev;
        const next = new Set(prev);
        next.add(dirRel);
        return next;
      });
    }
  }

  const ctxItems: ContextMenuItem[] = ctx
    ? [
        {
          label: t(revealLabelKey(platform)),
          icon: nodeIsDirectory(ctx.node) ? <FolderIcon size={14} /> : <ExternalLink size={14} />,
          onClick: () => void revealInFileManager(ctx.node),
        },
        ...(isRemovable(ctx.node, folder)
          ? [
              {
                label: t("remove.action"),
                icon: <Trash2 size={14} />,
                onClick: () => void startRemoval(ctx.node),
              },
            ]
          : []),
      ]
    : [];

  return (
    <div className="body browser">
      <aside className="sidebar browser-sidebar">
        <div className="side-head row wrap">
          {FOLDERS.map((f) => (
            <button key={f.id} className={`badge folder-tab mono${mode === "files" && folder === f.id ? " accent" : ""}`} onClick={() => { setFolder(f.id); setMode("files"); setSelected(null); setExpanded(new Set()); }}>
              <span className="dot" /> {t(f.labelKey)}
            </button>
          ))}
          <button className={`badge folder-tab mono${mode === "graph" ? " accent" : ""}`} onClick={() => { setMode("graph"); setSelected(null); }} title={t("nav.graph")}>
            <Share2 size={12} /> {t("nav.graph")}
          </button>
        </div>
        {mode === "files" && (
          <>
            <div className="folder-head">
              <span>{FOLDERS.find((f) => f.id === folder) ? t(FOLDERS.find((f) => f.id === folder)!.labelKey) : ""}</span>
              <span className="count">{nodes.length}</span>
            </div>
            {nodes.length === 0 ? (
              <div className="browser-empty">{t("browser.emptyFiles")}</div>
            ) : (
              <div className="browser-tree">
                <FileTree
                  nodes={tree.children}
                  folder={folder}
                  selected={selected}
                  expanded={expanded}
                  onToggleDir={toggleDir}
                  onSelectFile={setSelected}
                  onContextMenu={handleContextMenu}
                />
              </div>
            )}
            {folder === "input" && (
              <div className="side-head">
                <button className="btn btn-sm btn-primary btn-block" onClick={() => void addFiles()}><Plus size={14} /> {t("browser.addFiles")}</button>
              </div>
            )}
          </>
        )}
      </aside>
      <main className={`pane grow${mode === "graph" ? "" : " preview"}`}>
        {mode === "graph" ? (
          <GraphView />
        ) : (
          <>
            {!preview && <div className="empty"><div className="glyph"><FileText size={28} /></div><div className="e-title">{t("browser.selectFile")}</div></div>}
            {preview && (
              <>
                <div className="pv-head">
                  {preview.frontmatter && <h2 className="pv-title">{preview.frontmatter.title}</h2>}
                  <div className="pv-id mono">{preview.relativePath}</div>
                </div>
                {preview.frontmatter && (
                  <div className="pv-tags">
                    <span className="badge accent mono">{preview.frontmatter.type}</span>
                  </div>
                )}
                {preview.truncated && (
                  <div className="pv-tags">
                    <span className="pv-note">{t("preview.truncated")}</span>
                    <button className="btn btn-sm" onClick={() => void revealSelectedFile()}>
                      <ExternalLink size={14} /> {t(revealLabelKey(platform))}
                    </button>
                  </div>
                )}
                <div className="pv-body">
                  {preview.kind === "markdown" ? (
                    <MarkdownView
                      source={preview.content}
                      basePath={preview.relativePath}
                      onOpenFolder={openFolderLink}
                    />
                  ) : preview.kind === "binary" ? (
                    <div className="empty grow">
                      <div className="glyph"><FileText size={28} /></div>
                      <div className="e-title">{t("preview.binaryTitle")}</div>
                      <div className="e-sub">{preview.content}</div>
                      <button
                        className="btn btn-sm btn-primary"
                        onClick={() => void revealSelectedFile()}
                      >
                        <ExternalLink size={14} /> {t(revealLabelKey(platform))}
                      </button>
                    </div>
                  ) : (
                    <pre className="pv-text">{preview.content}</pre>
                  )}
                </div>
              </>
            )}
          </>
        )}
      </main>
      {ctx && <ContextMenu position={ctx.position} items={ctxItems} onClose={() => setCtx(null)} />}
      {removal && (
        <RemoveConceptModal
          plan={removal.plan}
          busy={removing}
          onConfirm={() => void confirmRemoval()}
          onCancel={() => setRemoval(null)}
        />
      )}
    </div>
  );
}

/** Type guard kept local so the menu icon reflects folder vs file. */
function nodeIsDirectory(node: TreeNode): boolean {
  return node.isDirectory;
}